accounts/urls.py
from django.urls import path, include
from django.contrib.auth.views import login, logout
from accounts.views import cadastrar
from accounts.forms import LoginForm

app_name = 'conta'

urlpatterns = [
    path('cadastrar-se/', cadastrar, name='cadastrar_se'),
    path('entrar/', login, {'template_name': 'accounts/login.html', 'authentication_form': LoginForm}, name='login'),
    path('sair/', logout, name='logout')
]

sebo/urls.py
from django.urls import path
from sebo.views import index, search, detalhes_livro, detalhes_vendedor, add_livro

app_name = 'sebo'


urlpatterns = [
    path('', index, name='index'),
    path('search/', search, name='search'),
    path('livros/<slug:slug>/', detalhes_livro, name="detalhes_livro"),
    path('vendedores/<slug:slug>/livros', detalhes_vendedor, name="detalhes_vendedor"),
    path('vendedores/<slug:slug>/livros/vender_livro', add_livro, name="vender_livro")
    ]

sebomania/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('sebo.urls', namespace='sebo')),
    path('conta/', include('accounts.urls', namespace='conta'))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)


if settings.DEBUG:
    import debug_toolbar
    urlpatterns.append(path(r'^__debug__/', include(debug_toolbar.urls)))

sebo/models.py
import itertools
from decimal import Decimal
from django.db import models
from django.urls import reverse
from django.utils.text import slugify
from django.contrib.auth.models import User
from django.db.models.signals import post_save
from django.dispatch import receiver
from django.core.validators import MinValueValidator


class Vendedor(models.Model):

    nome = models.CharField('Nome do sebo', max_length=100)
    sobre = models.TextField('Sobre', max_length=200, blank=True, null=True)
    cadastrado_em = models.DateTimeField('Data de cadastro', auto_now_add=True)
    slug = models.SlugField('Slug')

    user = models.OneToOneField(User, on_delete=models.CASCADE)

    SLUG_FIELDS = ['nome']


    def get_absolute_url(self):
        return reverse('sebo:detalhes_sebo', kwargs={'slug': self.slug})


    class Meta:
        verbose_name = 'sebo'
        verbose_name_plural = 'sebos'
        indexes = [
            models.Index(fields=['slug'])
        ]


def generate_slug(model, fields=None):
    fields = fields or model.SLUG_FIELDS
    dados_para_slug = '-'.join([getattr(model, field) for field in fields ])

    slug = slugify(dados_para_slug)

    total = model.__class__.objects.filter(slug=slug).count()

    if total:
        for x in itertools.count(total):
            slug_pesquisar = slug + '-' + str(x)

            if not model.__class__.objects.filter(slug=slug_pesquisar).exists():
                model.slug = slug_pesquisar
                break

    else:
        model.slug = slug

@receiver(post_save, sender=User)
def criar_vendedor(sender, instance, created, **kwargs):
    if created:
        if not (instance.is_superuser or instance.is_staff):
            nome_completo = instance.first_name

            if instance.last_name:
                nome_completo = nome_completo + ' ' + instance.last_name

            v = Vendedor(nome=nome_completo, user=instance)
            generate_slug(v, ['nome'])

            v.save()


class Autor(models.Model):

    nome = models.CharField('Nome', max_length=60)
    sobre = models.TextField('Sobre', max_length=200, null=True)
    slug = models.SlugField('Slug')


    class Meta:
        verbose_name = 'autor'
        verbose_name_plural = 'autores'

    def __str__(self):
        return self.nome


class Livro(models.Model):

    nome = models.CharField('Nome', max_length=150)
    descricao = models.TextField('Descrição', max_length=1200, null=True)
    ano = models.IntegerField('Ano de lançamento')
    qtd_paginas = models.PositiveIntegerField('Quantidade de Páginas')
    cadastrado_em = models.DateTimeField('Cadastrado em', auto_now_add=True)
    atualizado_em = models.DateTimeField('Atualizado_em', auto_now=True)
    slug = models.SlugField('Slug')

    foto = models.ImageField(verbose_name='Foto do livro',
                             upload_to='imagens_livros', blank=True,
                             null=True)

    autores = models.ManyToManyField(Autor)
    vendedor = models.ForeignKey(Vendedor, on_delete=models.CASCADE)
    preco = models.DecimalField('Preço', max_digits=12, decimal_places=2,
                                validators=[MinValueValidator(Decimal('1.0'))])

    SLUG_FIELDS = ('nome', 'nome_autores')


    def get_absolute_url(self):
        return reverse('sebo:detalhes_livro', kwargs={'slug': self.slug})

    @property
    def nome_autores(self):
        return ','.join([autor.nome for autor in self.autores.all()])

    class Meta:
        verbose_name = 'livro'
        verbose_name_plural = 'livros'
        indexes = [
            models.Index(fields=['slug'])
        ]

sebo/forms.py
import operator
from functools import reduce
from django import forms
from django.forms import ModelForm
from django.db.models import Q
from sebo.models import Livro, Autor, Vendedor, generate_slug

class BookSearch(forms.Form):

    q = forms.CharField(label='Pesquisa',
                             max_length=100,
                             required=True,
                             widget=forms.TextInput(attrs={'placeholder': 'Que livro você procura?',
                                                           'class': 'input is-medium'}))


class VendedorForm(ModelForm):

    class Meta:
        model = Vendedor
        fields = ['nome', 'sobre']

    def save(self, commit=True):
        generate_slug(self.instance)

        return super(VendedorForm, self).save()


class LivroForm(ModelForm):

    autores = forms.CharField(
        label='Autores',
        help_text='Use a vírgula para separar múltiplos autores',
        required=True
        )

    class Meta:
        model = Livro
        fields = ['nome', 'descricao', 'ano', 'qtd_paginas', 'foto', 'preco']

    def __init__(self, *args, **kwargs):
        super(LivroForm, self).__init__(*args, **kwargs)

        for field in self.fields.values():
            field.widget.attrs.update({'class': 'input'})

        self.fields['descricao'].widget.attrs.update({'class': 'textarea'})

    def save(self, commit=True):
        autores = []
        autores_form = self._get_autores()

        qs = [Q(nome__iexact=autor) for autor in autores_form]

        if len(qs) == 1:
            qs = qs[0]
        else:
            qs = reduce(operator.or_, qs)

        autores_filtrados = Autor.objects.filter(qs)

        if len(autores_filtrados) != len(autores_form): # TODO: problema com nomes iguais
            autores_nao_cadastrados = set([x.lower() for x in autores_form]) - set([autor.nome.lower() for autor in autores_filtrados])

            for nome in autores_nao_cadastrados:
                autor = Autor(nome=nome)
                autor.save()

                autores.append(autor)

        for autor in autores_filtrados:
            autores.append(autor)


        livro = super(LivroForm, self).save()
        self.instance.autores.set(autores)

        if commit:
            livro.save()
            generate_slug(self.instance)
            livro.save()

        return livro

    def _get_autores(self, sep=','):
        return self.cleaned_data['autores'].split(sep)

sebo/views.py
from django.core.paginator import Paginator
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.decorators import login_required
from django.conf import settings
from sebo.models import Vendedor, Livro
from sebo.forms import BookSearch, LivroForm


def index(request):
    template_name = 'sebo/index.html'
    context = {}

    ultimos_sebos = Vendedor.objects.order_by('-cadastrado_em')[:10]
    qtd_sebos = Vendedor.objects.count()
    qtd_livros = Livro.objects.count()

    context['ultimos_sebos'] = ultimos_sebos
    context['qtd_sebos'] = qtd_sebos
    context['search_form'] = BookSearch()
    context['qtd_livros'] = qtd_livros
    context['title'] = 'Livros novos e usados'

    return render(request, template_name, context)


def search(request):
    template_name = 'sebo/book_search.html'
    context = {'title': 'Busca'}

    if request.method == 'GET':
        search_form = BookSearch(request.GET)

        if search_form.is_valid():
            resultado_busca = Livro.objects.prefetch_related('autores').filter(nome__icontains=search_form.cleaned_data['q'])

            paginador = Paginator(resultado_busca, 20)
            pagina = request.GET.get('page', 1)

            context['resultado_busca'] = paginador.get_page(pagina)
            context['qtd_livros_encontrados'] = paginador.count
            context = {'title': 'Busca por ' + search_form.cleaned_data['q']}

            return render(request, template_name, context)
        else:
            # TODO: colocar mensagem
            pass

    return redirect('')


def detalhes_livro(request, slug):
    template_name = 'sebo/book.html'
    context = {}

    livro = get_object_or_404(Livro, slug=slug)

    context['livro'] = livro

    return render(request, template_name, context)


def detalhes_vendedor(request, slug):
    context = {}
    template_name = 'sebo/vendedor.html'

    vendedor = get_object_or_404(Vendedor.objects.select_related('user'), slug=slug)

    eh_dono_visualizando = request.user.pk == vendedor.user.pk
    paginador = Paginator(Livro.objects.prefetch_related('autores').filter(vendedor__id=1), 10)
    pagina = request.GET.get('page')
    livros = paginador.get_page(pagina)

    context['vendedor'] = vendedor
    context['livros'] = livros
    context['eh_o_dono_visualizando'] = eh_dono_visualizando
    context['qtd_livros'] = paginador.count

    if eh_dono_visualizando:
        context['title'] = 'Meus livros'
    else:
        nome_vendedor = vendedor.nome
        if nome_vendedor:
            context['title'] = nome_vendedor

    return render(request, template_name, context)


@login_required
def add_livro(request, slug):
    context = {}
    template_name = 'sebo/add_livro.html'
    form = LivroForm()

    if request.method == 'POST':
        vendedor = get_object_or_404(Vendedor, user=request.user)

        if request.user != vendedor.user:
            return redirect(settings.LOGIN_URL)

        form = LivroForm(request.POST, request.FILES, instance=Livro(vendedor=vendedor))

        if form.is_valid():
            livro = form.save()

            return redirect(livro)

    context['form'] = form
    context['title'] = 'Vender um livro'

    return render(request, template_name, context)

sebo/templates/sebo/add_livro.html
{% extends "sebo/template.html" %}
{% block content %}
<section class="section">
  <div class="section container is-desktop">
    <div class="columns">
      <div class="column is-half is-offset-one-quarter">
        <div class="content">
          <h1 class="title">Novo livro à venda</h1>
          <form method="post" enctype="multipart/form-data">
            {% csrf_token %} {{ form.non_field_errors }}
            {% for field in form %}
            <div class="field">
              <label class="label" for="{{ field.id_for_label}}">{{ field.label }}</label>

              <div class="control">
                {{ field }}
              </div>
              <p class="help">
                {{field.help_text}}
              </p>
              {% if field.errors %}
              <p class="help is-danger">{{ field.errors }}</p>
              {% endif %}

            </div>
            {% endfor %}
            <div class="field">
              <div class="control">
                <button type="submit" class="button is-primary">Cadastrar Livro</button>
              </div>
            </div>
          </form>
        </div>

      </div>
    </div>
  </div>
</section>
{% endblock %}

sebo/templates/sebo/base_template.html
<!DOCTYPE html>
<html>
  {% load static %}
  <title>{{title}}</title>
  <head>
    <meta charset="utf-8"/>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bulma/0.6.2/css/bulma.min.css" />
    {% block styles %}
    {% endblock %}
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
  </head>
  <body>
    {% block pre_content %}
    {% endblock %}
    {% block content %}
    {% endblock %}
  </body>
</html>

sebo/templates/sebo/book.html
{% extends "sebo/template.html" %}
{% block content %}
{% load sebo_tags %}
<section class="section">
  <div class="section container is-desktop">
    <div class="columns">
      <div class="column is-three-fifths is-offset-1">
        <article class="media">
          <div class="media-left">
            <figure class="image is-128x128">
              {% if livro.foto %}
              <img src="{{livro.foto.url}}">

              {% else %}
              <img src="https://bulma.io/images/placeholders/128x128.png">
              {% endif %}
            </figure>
          </div>
          <div class="media-content">
            <div class="content">
              <h2>{{livro.nome}}</h2> {% if livro.nome_autores %} {{ livro.nome_autores}} <br/>{% endif %}
              <small>
                  {% if livro.qtd_paginas %}<strong>Páginas</strong>: {{livro.qtd_paginas}} <br/>{% endif %}
                  {% if livro.ano %}<strong>Ano</strong>: {{livro.ano}} <br/>{% endif %}
                  <strong>Atualizado em</strong>: {{livro.atualizado_em}}<br/>
                  <strong>Descrição</strong>: {{livro.descricao|linebreaks}}
                  </small>
            </div>
          </div>
        </article>
      </div>
      <div class="column">
        <div class="content">
          <h2>{{ livro.preco|formatar_moeda }}<h2>
          <p><a class="button is-danger is-large">Comprar</a></p>
          <h4>Sobre o Vendedor</h4>
          <p><a href="{{livro.vendedor.get_absolute_url}}">{{livro.vendedor.nome}}</a></p>
        </div>
      </div>
    </div>
  </div>
</section>

{% endblock %}

sebo/templates/sebo/book_search.html
{% extends "sebo/template.html" %}
{% block content %}
{% load sebo_tags %}
<section class="section">
  <div class="section container is-desktop">
    <div class="columns">
      <div class="column is-three-fifths is-offset-one-fifth">
        <div class="content">
          {% if resultado_busca %}
          <h1>{{qtd_livros_encontrados}} Livro(s) encontrado(s)</h1> {% for livro in resultado_busca %}
          <div class="box">
            <article class="media">
              <div class="media-left">
                <figure class="image is-96x96">
                  {% if livro.foto %}
                  <img src="{{livro.foto.url}}">

                  {% else %}
                  <img src="https://bulma.io/images/placeholders/128x128.png">
                  {% endif %}
                </figure>
              </div>
              <div class="media-content">
                <div class="content">
                  <p>
                    <strong><a href="{{livro.get_absolute_url}}">{{livro.nome}}</a></strong>
                    <br/> {{livro.nome_autores}}
                    <br/>
                    <small>
                          {% if livro.ano %}<strong>Ano</strong>: {{livro.ano}}{% endif %}
                          <br/>
                          {{livro.descricao}}
                        </small>
                  </p>
                </div>
              </div>
            </article>
          </div>
          {% endfor %}
          {% else %}
          <h1 class="has-text-centered">Nenhum livro encontrado</h1>
          {% endif %}

        </div>
        {% if resultado_busca.has_other_pages %}
        <nav class="pagination" role="navigation" aria-label="pagination">
          {% if resultado_busca.has_previous %}
          <a href="?{% url_replace page=resultado_busca.previous_page_number %}" class="pagination-previous">Anterior</a>
          {% endif %}
          {% if resultado_busca.has_next %}
          <a href="?{% url_replace page=resultado_busca.next_page_number %}" class="pagination-next">Próximo</a>
          {% endif %}

          <ul class="pagination-list">
            {% for i in resultado_busca.paginator.page_range %}
            <li>
              <a href="?{% url_replace page=i %}"class="pagination-link {% if i == resultado_busca.number %}is-current{%endif%}" aria-label="Ir para a página {{i}}">{{i}}</a>
            </li>
            {% endfor %}
          </ul>
          {% endif %}
        </nav>
      </div>
    </div>
  </div>
</section>

{% endblock %}

sebo/templates/sebo/book_search_nav.html
<form action="/search" method="get">
  <div class="field has-addons has-addons-centered">
    <div class="control">
      {{search_form.q}}
    </div>
    <div class="control">
      <button type="submit" class="button is-primary">Pesquisar</button>
    </div>
  </div>
</form>

sebo/templates/sebo/index.html
{% extends "sebo/base_template.html" %}

{% block pre_content %}
{% include "sebo/nav.html"%}
{% endblock %}

{% block content %}

<section class="hero is-fullheight is-info">
  <div class="hero-body">
    <div class="container has-text-centered">
      <h1 class="title">Milhares de livros novos e usados</h1>
      <form action="/search" method="get">
        <div class="field has-addons has-addons-centered">
          <div id="index-search-container" class="control">
            {{search_form.q}}
            <!--<input class="input is-medium" type="text" placeholder="ll"> -->
          </div>
          <div class="control">
            <button id="bt-procurar" type="submit" class="button is-primary is-medium">
              Procurar
            </button>
          </div>
        </div>
      </form>
    </div>
  </div>
</section>
{% endblock %}

sebo/templates/sebo/nav.html
{% load static %}
{% load sebo_tags %}
<nav class="navbar is-fixed-top {{nav_classes}}" role="navigation" aria-label="main navigation">
  <div class="navbar-brand">
    <a class="navbar-item" href="/">
      <img src="{% static 'images/scholarship.png' %}">
    </a>

    <button class="button navbar-burger">
      <span></span>
      <span></span>
      <span></span>
    </button>
  </div>

  <div class="navbar-menu">
    <div class="navbar-start">
    </div>

    <div class="navbar-end">
      {% if nav_search %}
      <div class="navbar-item">
        <p class="control">
            {% show_book_search_nav %}
        </p>
      </div>
      {% endif %}
      <div class="navbar-item">
        {% if not user.is_authenticated %}
        <p class="control">
          <a class="button is-white" href="{% url 'conta:login' %}">
            Entrar
          </a>
        </p>
      </div>

      <div class="navbar-item">
        <p class="control">
          <a class="button is-success" href="{% url 'conta:cadastrar_se' %}">
            Cadastrar-se
          </a>
        </p>
      </div>
      {% else %}
      <div class="navbar-item">
        <p>
          <a class="button is-white" href="{% url 'sebo:detalhes_vendedor' slug=user.vendedor.slug %}">Meus livros</a>
        </p>
      </div>
      <div class="navbar-item">
        <p>
          <a class="button is-danger" href="{% url 'sebo:vender_livro' slug=user.vendedor.slug %}">Vender um livro</a>
        </p>
      </div>
      <div class="navbar-item">
        <p>
          <a class="button" href="{% url 'conta:logout' %}">Sair</a>
        </p>
      </div>


      {% endif %}

    </div>

  </div>
</nav>

sebo/templates/sebo/template.html
{% extends "sebo/base_template.html" %}

{% block pre_content %}
{% include "sebo/nav.html" with nav_classes="nav-header" nav_search=True%}
{% endblock%}

sebo/templates/sebo/vendedor.html
{% extends "sebo/template.html" %}
{% load static %}
{% load sebo_tags %}
{% block content %}
{% if eh_o_dono_visualizando and not qtd_livros %}
<section class="hero is-fullheight is-light">
  <div class="hero-body">
    <div class="container has-text-centered">
      <figure class="image is-128x128" style="margin-left: auto; margin-right: auto; margin-bottom: 16px">
        <img src="{%static 'images/sad.png' %}"/>
      </figure>
      <h1 class="title">Você não tem nenhum livro à venda</h1>
      <a class="button is-danger" href="{%url 'vendedor:vender_livro' slug=user.vendedor.slug %}">Quero vender um livro</a>
    </div>
  </div>
</section>
{% elif qtd_livros %}
<section class="section">
  <div class="section container is-desktop">
    <div class="columns">
      <div class="column is-half is-offset-one-quarter">
        <div class="content">
          <h1>{{vendedor.nome}}</h1>
          <strong>Cadastrado em</strong>: {{vendedor.cadastrado_em|date:'d/m/Y'}}
          <br/> {% if vendedor.sobre %} {{vendedor.sobre|linebreaks}} {% endif %}
          {% if qtd_livros %}
          <h2>Livros</h2>
          {% for livro in livros %}
          <div class="box">
            <article class="media">
              <div class="media-left">
                <figure class="image is-96x96">
                  {% if livro.foto %}
                  <img src="{{livro.foto.url}}">
                  {% else %}
                  <img src="https://bulma.io/images/placeholders/128x128.png">
                  {% endif %}
                </figure>
              </div>
              <div class="media-content">
                <div class="content">
                  <p>
                    <strong><a href="{{livro.get_absolute_url}}">{{livro.nome}}</a></strong>
                    <br/> {{livro.nome_autores}}
                    <br/>
                    <small>
                          {% if livro.ano %}<strong>Ano</strong>: {{livro.ano}}{% endif %}
                          <br/>
                          {{livro.descricao}}
                        </small>
                  </p>
                </div>
              </div>
            </article>
          </div>
          {% endfor %}

        {%endif %}
        </div>
        {% if livros.has_other_pages  %}
        <nav class="pagination" role="navigation" aria-label="pagination">
          {% if livros.has_previous %}
          <a href="?{% url_replace page=livros.previous_page_number %}" class="pagination-previous">Anterior</a>
          {% endif %}
          {% if livros.has_next %}
          <a href="?{% url_replace page=livros.next_page_number %}" class="pagination-next">Próximo</a>
          {% endif %}

          <ul class="pagination-list">
            {% for i in livros.paginator.page_range %}
            <li>
              <a href="?{% url_replace page=i %}"class="pagination-link {% if i == livros.number %}is-current{%endif%}" aria-label="Ir para a página {{i}}">{{i}}</a>
            </li>
            {% endfor %}
          </ul>

        </nav>
        {% endif %}

      </div>
    </div>
  </div>
</section>
{% else %}
<section class="hero is-fullheight is-light">
  <div class="hero-body">
    <div class="container has-text-centered">
      <figure class="image is-128x128" style="margin-left: auto; margin-right: auto; margin-bottom: 16px">
        <img src="{%static 'images/sad.png' %}"/>
      </figure>
      <h1 class="title">Nenhum livro à venda</h1>
    </div>
  </div>
</section>
{% endif %}

{% endblock %}